#!/usr/bin/env bash
# Build docs/review/FINDINGS.md from every review findings file.
#
#   tools/findings.sh            # print it
#   tools/findings.sh --write    # write docs/review/FINDINGS.md
#   tools/findings.sh --open     # only findings still awaiting a Resolution
#
# Generated, like docs/REGISTER.md: on a merge conflict you regenerate, you
# never merge. One review round writes one file and exactly one session owns
# it, so this only ever reads.
#
# The check that matters: the findings template says a fixer leaves no finding
# at `open` without a Resolution line, and that "ran out of time" is acceptable
# while silence is not. --open is what makes that mechanical instead of a
# matter of remembering.

set -uo pipefail
cd "${REPO:-/home/user/redmine}" || exit 2

MODE="${1:-print}"
python3 - "$MODE" <<'PY'
import glob, os, re, sys

mode = sys.argv[1]
RANK = {'blocker': 0, 'major': 1, 'minor': 2, 'nit': 3, 'question': 4}

def field(block, name):
    m = re.search(r'^-\s+\*\*%s:\*\*\s*(.*)$' % name, block, re.M)
    return m.group(1).strip() if m else ''

KNOWN = sorted(
    (os.path.basename(d) for d in glob.glob('docs/features/*') if os.path.isdir(d)),
    key=len, reverse=True)

rows, files = [], []
for path in sorted(glob.glob('docs/review/findings/*.md')):
    if os.path.basename(path) == 'TEMPLATE.md':
        continue
    text = open(path, encoding='utf-8').read()
    head = text.split('\n### ', 1)[0]
    base = os.path.basename(path)[:-3]
    date, rest = (base[:10], base[11:]) if re.match(r'\d{4}-\d{2}-\d{2}-', base) else ('', base)
    # Slug and reviewer are both dashed, so splitting on dashes cannot tell them
    # apart. The feature directories are the authority on which slugs exist.
    slug = max((d for d in KNOWN if rest.startswith(d + '-')), key=len, default='')
    reviewer = rest[len(slug) + 1:] if slug else rest
    if not slug:
        slug = rest
    counts = ''
    cm = re.search(r'^\*\*Counts:\*\*\s*(.*)$', head, re.M)
    if cm:
        counts = cm.group(1).replace('·', '/').strip()
    ran = field(head, 'Ran the test suite')
    files.append((slug, date, reviewer, counts, ran, path))

    for chunk in re.split(r'^### ', text, flags=re.M)[1:]:
        title = chunk.split('\n', 1)[0].strip()
        fid, _, label = title.partition('—')
        sev = field(chunk, 'Severity').split('|')[0].strip().lower()
        res = field(chunk, 'Resolution')
        rows.append({
            'slug': slug, 'id': fid.strip(), 'label': label.strip(),
            'sev': sev if sev in RANK else 'minor',
            'status': field(chunk, 'Status').lower(),
            'cat': field(chunk, 'Category').split('|')[0].strip(),
            'conf': field(chunk, 'Confidence').split('|')[0].strip(),
            'where': field(chunk, 'Where'),
            'res': res,
        })

if mode == '--open':
    rows = [r for r in rows if not r['res']]

rows.sort(key=lambda r: (RANK.get(r['sev'], 9), r['slug'], r['id']))

out = []
w = out.append
w('<!-- GENERATED by tools/findings.sh from docs/review/findings/*.md.')
w('     Do not edit. On a merge conflict, regenerate instead of merging. -->')
w('')
w('# FINDINGS — elke reviewbevinding, één regel elk')
w('')
if not files:
    w('Nog geen reviews.')
else:
    tally = {}
    for r in rows:
        tally[r['sev']] = tally.get(r['sev'], 0) + 1
    unresolved = sum(1 for r in rows if not r['res'])
    w('%d bevindingen uit %d reviews: %s. **%d zonder Resolution-regel.**' % (
        len(rows), len(files),
        ', '.join('%d %s' % (tally[k], k) for k in sorted(tally, key=lambda x: RANK.get(x, 9))) or 'geen',
        unresolved))
    w('')
    w('| Sev | Slug | ID | Bevinding | Cat | Zekerheid | Waar | Resolution |')
    w('|---|---|---|---|---|---|---|---|')
    for r in rows:
        w('| %s | `%s` | %s | %s | %s | %s | %s | %s |' % (
            r['sev'], r['slug'], r['id'], r['label'], r['cat'], r['conf'],
            r['where'] if '`' in r['where'] else (('`%s`' % r['where']) if r['where'] else ''),
            r['res'] or '**—**'))
    w('')
    w('## Per review')
    w('')
    w('| Slug | Datum | Reviewer | Counts | Suite gedraaid |')
    w('|---|---|---|---|---|')
    for slug, date, reviewer, counts, ran, path in files:
        w('| [`%s`](findings/%s) | %s | %s | %s | %s |' % (
            slug, os.path.basename(path), date, reviewer, counts, ran[:60]))
doc = '\n'.join(out) + '\n'
if mode == '--write':
    with open('docs/review/FINDINGS.md', 'w', encoding='utf-8') as fh:
        fh.write(doc)
    print('wrote docs/review/FINDINGS.md — %d finding(s) from %d review(s)' % (len(rows), len(files)))
else:
    print(doc, end='')
PY
