#!/usr/bin/env bash
# Build docs/REGISTER.md from the per-feature status files.
#
#   tools/register.sh            # print it
#   tools/register.sh --write    # write docs/REGISTER.md
#
# The register used to be a table inside docs/STATE.md, which every session
# rewrote — so two parallel sessions fought over it and the loser's row
# disappeared. It is now DERIVED from the front matter of each
# docs/features/<slug>/status.md, which exactly one session owns.
#
# That makes the conflict harmless instead of dangerous: REGISTER.md is
# generated, so if a replay ever conflicts on it you do not merge it, you
# regenerate it.

set -uo pipefail

REPO="${REPO:-/home/user/redmine}"
cd "$REPO" || { echo "FAIL  repo not found: $REPO" >&2; exit 2; }

OUT=$(python3 - <<'PY'
import glob, os, re, sys

ORDER = ['todo', 'ontworpen', 'patch klaar', 'ingediend', 'geaccepteerd',
         'afgewezen', 'nooit', 'vervallen']

def front_matter(path):
    fields, lines = {}, open(path, encoding='utf-8').read().splitlines()
    if not lines or lines[0].strip() != '---':
        return None
    for line in lines[1:]:
        if line.strip() == '---':
            break
        m = re.match(r'([a-z_][a-z_0-9]*):\s*(.*)$', line)
        if m:
            v = m.group(2).strip()
            if len(v) > 1 and v[0] == v[-1] and v[0] in '"\'':
                v = v[1:-1]
            fields[m.group(1)] = v
    return fields

def body_section(path, heading):
    out, on = [], False
    for line in open(path, encoding='utf-8').read().splitlines():
        if line.startswith('## '):
            on = line[3:].strip().lower().startswith(heading.lower())
            continue
        if on:
            out.append(line)
    return '\n'.join(out).strip()

rows, waiting, missing = [], [], []
for path in sorted(glob.glob('docs/features/*/status.md')):
    slug = os.path.basename(os.path.dirname(path))
    f = front_matter(path)
    if f is None:
        missing.append(path)
        continue
    f['slug'] = slug
    f['_path'] = path
    rows.append(f)
    todo = body_section(path, 'Wat Jan nog moet doen')
    if todo and todo not in ('-', 'niets', 'Niets'):
        waiting.append((slug, todo))

claims = {}
for path in glob.glob('docs/claims/*--*'):
    slug = os.path.basename(path).split('--')[0]
    claims.setdefault(slug, []).append(path)

def sort_key(r):
    up = r.get('upstream', 'todo')
    return (ORDER.index(up) if up in ORDER else len(ORDER), r['slug'])

print('<!-- GENERATED by tools/register.sh from docs/features/*/status.md.')
print('     Do not edit. On a merge conflict, regenerate instead of merging. -->')
print()
print('# REGISTER — alle features, één regel elk')
print()
print('Afgeleid uit `docs/features/<slug>/status.md`. Elke feature heeft twee')
print('leveringen: **GEOxyz** (draait het in productie op 7.0?) en **Upstream**')
print('(waar staat de patch?).')
print()
print('| Slug | Feature | 5.1-commit | GEOxyz | Upstream | Issue |')
print('|---|---|---|---|---|---|')
for r in sorted(rows, key=sort_key):
    geo = r.get('geoxyz', '?')
    if r.get('geoxyz_commit'):
        geo = '%s (`%s`)' % (geo, r['geoxyz_commit'])
    issue = r.get('issue', '')
    issue = ('[#%s](https://www.redmine.org/issues/%s)' % (issue, issue)) if issue and issue != '-' else '—'
    print('| [`%s`](features/%s/status.md) | %s | `%s` | %s | %s | %s |'
          % (r['slug'], r['slug'], r.get('feature', '?'),
             r.get('commit_51', '?'), geo, r.get('upstream', '?'), issue))

counts = {}
for r in rows:
    counts[r.get('upstream', '?')] = counts.get(r.get('upstream', '?'), 0) + 1
print()
print('%d features: %s.' % (len(rows),
      ', '.join('%d %s' % (n, k) for k, n in sorted(counts.items(), key=lambda kv: -kv[1]))))

if claims:
    print()
    print('## Nu in behandeling')
    print()
    for slug in sorted(claims):
        who = []
        for p in sorted(claims[slug]):
            d = dict(l.split(': ', 1) for l in open(p, encoding='utf-8').read().splitlines() if ': ' in l)
            who.append('%s sinds %s' % (d.get('session', '?'), d.get('date', '?')))
        print('- `%s` — %s' % (slug, '; '.join(who)))

if waiting:
    print()
    print('## Openstaand voor Jan')
    print()
    for slug, todo in sorted(waiting):
        print('### `%s`' % slug)
        print()
        print(todo)
        print()

if missing:
    print()
    print('<!-- no front matter, not in the table: %s -->' % ', '.join(missing))
PY
) || { echo "FAIL  could not build the register" >&2; exit 1; }

if [ "${1:-}" = "--write" ]; then
  printf '%s\n' "$OUT" > docs/REGISTER.md
  echo "PASS  wrote docs/REGISTER.md ($(grep -c '^| \[' docs/REGISTER.md) features)"
else
  printf '%s\n' "$OUT"
fi
